### ISSUE TITLE
Add safe readers

### ISSUE THREAD

**Issue by fkromer** [raphaelm/defusedcsv#4]
Add safe [csv readers](https://docs.python.org/3.8/library/csv.html#reader-objects).

**Comment by raphaelm** [comment]
Can you describe an intended use case for this? There's nothing "unsafe" about loading CSVs in Python, this library is just about "safety when opening in Excel" which is only a concern during writing, is it not?

**Comment by fkromer** [comment]
You are right. The project description states that it's about csv export only. However the risk of importing dangerous payload is far bigger than exporting dangerous *.csv payload. Consider this common use case: You are running a `django` based backend with at least one model which allows to upload a *.csv file via `FileField`. The backend does processing on this file in the background. I'm pretty sure you don't want to process *.csv payload which is dangerous because it can lead to security issues. Your project could be extended easily with the "make import safe" part. And as far as I know there is no package which handles safe read yet. However if you prefer to stick to the write part only that's totally fine.

**Comment by raphaelm** [comment]
> The backend does processing on this file in the background. I'm pretty sure you don't want to process *.csv payload which is dangerous because it can lead to security issues.

How can a CSV payload be dangerous to your background processing?

**Comment by fkromer** [comment]
In my use case it's actually about to detect potentially dangerous csv files by reading them prior to allow an upload. After downloading the uploaded file the csv file could do harm on the user which downloaded the file.

Right. It's very unlikely that potential dangerous commands in csv file cells are run by the Python backend e.g. using `Popen` or something.

**Comment by raphaelm** [comment]
Yes, I think if escaping is not an option for you and you need to check during upload, you should use a regular reader and attempt writing it back using the new patch. Keep in mind, that this will create *LOTS* of false positives. Every CSV file with a column starting with a minus and not a number will be rejected, e.g.

**Comment by fkromer** [comment]
I know. In my case this is ok cause I know all possible good case input scenarios. As what I'm going to implement is application specific security related validation we can probably close this issue.
